config/routes.rb
Rails.application.routes.draw do

  get 'hashtags/show'

  root 'users#index'

  resources :users
  resource :session, only: [:new, :create, :destroy]
  resources :questions, except: [:show, :new, :index]
  resources :hashtags, only: [:show]
end

app/models/question.rb
class Question < ApplicationRecord
  # вопрос принадлежит пользователю
  belongs_to :user

  # у вопроса есть автор
  belongs_to :author, class_name: 'User', optional: true

  # у вопроса может быть много хэштегов
  has_and_belongs_to_many :hashtags

  # текст вопроса не должен быть пустым и быть длиннее 255 символов
  validates :text, :user, presence: true
  validates :text, length: { maximum: 255 }

  # перед сохранением модели, дергаем метод find_hashtags
  before_save :find_hashtags

  # метод нахождения хэштегов в тексте или ответе вопроса
  def find_hashtags
    # обнуляем массив с хэштегами перед нахождением новых, чтобы изавиться от старых
    self.hashtags = []

    # сканируем текст или ответ вопроса на наличие хэштегов, переводим найденные хэштеги в нижний регистр и
    # записываем все в массив hashtags_array
    hashtags_array = "#{text} #{answer}".scan(/#[а-яА-Яa-zA-z-]+[^0-9.<> ?!@#$%^&*()_]+/).map(&:downcase).uniq

    # создаем экземпляры модели Hashtag по имени и добавляем их в соединительнцю таблицу question.hashtags
    hashtags_array.each { |h| self.hashtags << Hashtag.find_or_create_by(name: h) }
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  # Инициализируем объект вопрос для экшенов кроме :edit, :update, :destroy
  before_action :load_question, only: [:show, :edit, :update, :destroy]

  # Проверяем имеет ли юзер доступ к экшену для всей дествий, кроме задавания
  # вопроса, это действие может вызвать даже неавторизованный пользователь.
  before_action :authorize_user, except: [:create]

  # Перед этим действием сработает before_action :load_questions и в переменной
  # @question у нас будет лежать вопрос с нужным id равным params[:id].
  def edit; end

  # Действие create будет отзываться при POST-запросе по адресу /questions из
  # формы нового вопроса, которая находится в шаблоне на странице
  # /questions/edit
  def create
    @question = Question.new(question_params)

    current_user.present? ? @question.author = current_user : @question.author = nil

    # проверка recaptcha на интернет-бота
    if verify_recaptcha(model: @question) && @question.save
      redirect_to user_path(@question.user), notice: "Вопрос задан."
    else
      render :edit
    end
  end

  # Перед этим действием сработает before_action :load_questions и в переменной
  # @question у нас будет лежать вопрос с нужным id равным params[:id].
  def update
    if @question.update(question_params)
      redirect_to user_path(@question.user), notice: 'Вопрос сохранен.'
    else
      render :edit
    end
  end

  # Удаляем вопрос
  def destroy
    user = @question.user
    @question.destroy

    # Редиректим пользователя на страницу пользователя
    redirect_to user_path(user), notice: 'Вопрос удален.'
  end

  private

  def load_question
    @question = Question.find(params[:id])
  end

  def authorize_user
    reject_user unless @question.user == current_user
  end

  def question_params
    if current_user.present? && params[:question][:user_id].to_i == current_user.id
      params.require(:question).permit(:user_id, :text, :answer, :hashtag)
    else
      params.require(:question).permit(:user_id, :text, :hashtag)
    end
  end
end

app/views/questions/_form.html.erb
<%# Форма для создания/правки вопроса %>
<div class="form">
  <%# Форма для объекта @question %>
  <%= form_for(@question) do |f| %>
      <% if @question.errors.any? %>
          <div class="form-errors">
            <ul>
              <% @question.errors.full_messages.each do |message| %>
                  <li class="form-error-message"><%= message %></li>
              <% end %>
            </ul>
          </div>
      <% end %>

      <%# Скрытое поле — айдишник юзера, кому задается вопрос %>
      <%= f.hidden_field :user_id %>

      <div class="form-field">
        <%= f.label :text, 'Вопрос', class: 'form-label' %>
        <%= f.text_area :text, class: 'form-textarea' %>
      </div>

      <%# Простая авторизация - может ли текущий юзер править вопрос? %>
      <% if current_user.present? && current_user == @question.user %>
          <div class="form-field">
            <%= f.label :answer, 'Ответ', class: 'form-label' %>
            <%= f.text_area :answer, class: 'form-textarea' %>
          </div>
      <% end %>

      <div>
        <%= recaptcha_tags %>
      </div>

      <div class="form-action buffer-both">
        <%= f.submit 'Сохранить', class: 'button button-dark button-small' %>
        или
        <%= link_to "вернуться", user_path(@question.user) %>
      </div>
  <% end %>
</div>

app/views/questions/_question.html.erb
<div class="question">
  <div class="question-content">
    <div class="question-text text-lead">
      <%= question.text %>
    </div>

    <!-- Если вопрос имеет ответ, показать его -->
    <% if question.answer.present? %>
      <div class="question-answer text-lead">
        <%= question.answer if question.answer.present? %>
      </div>
    <% end %>

    <div class="question-date">
      <!-- Локализованный вывод даты вопроса в коротком формате -->
      <%= l(question.created_at, format: :short) %>
    </div>
  </div>

  <div class="text-small text-blue">
    <!-- Выводим ссылки с хэштегами после вопроса -->
    <% question.hashtags.each do |hashtag| %>
      <%= link_to hashtag.name, hashtag_path(hashtag) %>
    <% end %>
  </div>

  <% if question.user == current_user %>
      <%# Определяем какая будет иконка, если у вопроса нет ответа, то иконка %>
      <%# овтета на письмо, иначе — карандашик %>
      <% edit_icon = question.answer.blank? ? 'reply' : 'pencil' %>

      <div class="question-actions">
        <%= link_to fa_icon(edit_icon), edit_question_path(question) %>
        <%= link_to fa_icon('trash-o'), question_path(question), method: :delete, data: {confirm: 'Точно удалить вопрос?'} %>
      </div>
  <% end %>

  <%# Выводим автора вопроса %>
  <div class="text-right">
    <% if question.author_id.class != NilClass %>
      <% find_question_author = User.find_by(id: question.author_id) %>
      <%= link_to "Автор вопроса: @#{find_question_author.name}", user_path(find_question_author) %>
    <% else %>
      <p>Вопрос задан анонимно</p>
    <% end %>
  </div>

  <%# Определяем кому задан вопрос %>
  <div class="text-right">
    <%= link_to "Задан пользователю: @#{question.user.name}", user_path(question.user) %>
  </div>
</div>

app/views/questions/edit.html.erb
<%# Страница редактирования вопроса %>
<div class="container content-wrapper buffer-both">
  <h1 class="title-medium">Вопрос</h1>

  <div class="column-1-2">
    <%# Подключаем паршиал app/views/questions/_form.html.erb %>
    <%= render 'form' %>
  </div>
</div>