config/routes.rb
Rails.application.routes.draw do

  get 'hashtags/show'

  root 'users#index'

  resources :users
  resource :session, only: [:new, :create, :destroy]
  resources :questions, except: [:show, :new, :index]
  resources :hashtags, only: [:show]
end

app/models/user.rb
require 'openssl'

class User < ApplicationRecord
  # параметры работы модуля шифрования паролей
  ITERATIONS = 20000
  DIGEST = OpenSSL::Digest::SHA256.new

  # эта команда добавляет связь с моделью Question на уровне объектов
  # она же добавляет метод .questions к данному объекту
  has_many :questions, dependent: :destroy

  # email и username не должны быть пустым
  validates :email, :username, presence: true

  # у каждого пользователя email и username должны быть уникальными (не должны повторяться)
  validates :email, :username, uniqueness: true

  # цвет шапки должен содержать только цифры и ровно 6
  validates :head_color, format: { with: /\A#[a-f0-9]{6}+\z/ }

  # проверка формата email
  validates :email, format: { with: /\A[a-zA-Z0-9._+]+@[a-zA-Zа-яА-Я._+]+\.[a-zа-я]+\z/, message: "it is not email" }

  # имя пользователя должно содерэать только буквы, цифры и знак _
  validates :username, format: { with: /\A[a-zA-Z0-9_]+\z/, message: "only letters, numbers and _" }

  # длина имени пользователя должна быть не больше 40 символов
  validates :username, length: { maximum: 40 }

  # виртуальное поле, которое не сохраняется в базу
  # из него перед сохранение читается пароль, и сохраняется в базу уже
  # зашифрованная версия пароля в реальные поля password_salt и password_hash
  attr_accessor :password

  validates_presence_of :password, on: :create

  validates_confirmation_of :password

  # перед проверками дкргаем метод convert_to_downcase
  before_validation :convert_to_downcase

  # понижаем регистр букв имени пользователя
  def convert_to_downcase
    username.downcase!
  end

  before_save :encrypt_password

  # шифруем пароль, если он задан
  def encrypt_password
    if self.password.present?
      # создаем т. н. "соль" - рандомная строка усложняющая задачу хакерам
      self.password_salt = User.hash_to_string(OpenSSL::Random.random_bytes(16))

      # создаем хэш пароля — длинная уникальная строка, из которой невозможно восстановить
      # исходный пароль
      self.password_hash = User.hash_to_string(
          OpenSSL::PKCS5.pbkdf2_hmac(self.password,self.password_salt, ITERATIONS, DIGEST.length, DIGEST)
      )
    end
  end

  # служебный метод, преобразующий бинарную строку в 16-ричный формат, для удобства хранения
  def self.hash_to_string(password_hash)
    password_hash.unpack('H*')[0]
  end

  # Основной метод для аутентификации юзера (логина)
  # Проверяет email и пароль, если пользователь с такой комбинацией есть в базе
  # возвращает этого пользователя.
  # Если нету — возвращает nil
  def self.authenticate(email, password)
    user = find_by(email: email) # сперва находим кандидата по email

    if user.present? && user.password_hash == User.hash_to_string(OpenSSL::PKCS5.pbkdf2_hmac(password, user.password_salt, ITERATIONS, DIGEST.length, DIGEST))
      user
    else
      nil
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # Инициализируем объект User для экшенов кроме :index, :create, :new
  before_action :load_user, except: [:index, :create, :new]

  # Проверяем имеет ли юзер доступ к экшену для всей дествий, кроме index, new, create, show
  before_action :authorize_user, except: [:index, :new, :create, :show]

  # Экшен index со списком всех юзеров
  def index
    @users = User.all
    @all_questions = Question.all
  end

  # Экшен new создает нового пользователя, но пока не добавляет в базу
  def new
    redirect_to root_url, alert: 'Вы уже залогинены' if current_user.present?
    @user = User.new
  end

  # Экшен create сохраняет и добавляет в базу нового пользователя
  def create
    redirect_to root_url, alert: 'Вы уже залогинены' if current_user.present?

    # Достаем пользователя со всеми его параметрами (полями), которые были заданы
    @user = User.new(user_params)

    if @user.save
      session[:user_id] = @user.id

      # Редиректим на страницу пользователя с сообщением
      redirect_to user_path(@user), notice: 'Пользователь успешно зарегистрирован!'
    else
      render 'new'
    end
  end

  # Удаление пользователя
  def destroy
    @user.destroy

    # Редиректим на главную с сообщением
    redirect_to root_url, notice: 'Ваш аккаунт удален'
  end

  def edit; end

  # Обновление параметров пользователя
  def update
    if @user.update(user_params)

      # Редиректим на страницу пользователя с сообщением
      redirect_to user_path(@user), notice: 'Данные обновлены!'
    else

      # иначе рендерим пустой экшен edit
      render 'edit'
    end
  end

  def show
    @questions = @user.questions.order(created_at: :desc)
    @new_question = @user.questions.build

    # Создаем три переменные с количеством вопросов, отвеченных вопросов и
    # неотвеченных вопросов
    @questions_count = @questions.count
    @answers_count = @questions.where.not(answer: nil).count
    @unanswered_count = @questions_count - @answers_count

    @text = nil
  end

  private

  def authorize_user
    reject_user unless @user == current_user
  end

  def load_user
    @user ||= User.find params[:id]
  end

  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation, :head_color, :name, :username, :avatar_url)
  end
end

app/views/users/edit.html.erb
<%# Страница редактирования пользователя %>

<div class="container content-wrapper buffer-both">
  <h1 class="title-medium">Править профиль</h1>

  <div class="column-1-2">
    <%# С помощью специального хелпера form_for мы делаем тег <form ...> %>
    <%# с нужными аттрибутами, после этого в переменной f будет специальный %>
    <%# объект (form builder object), вызывая методы которого мы можем %>
    <%# создавать теги для нужных нам полей формы. %>
    <%= form_for(@user) do |f| %>
        <%# Вывод ошибок валидации пользователя, если есть. Ошибки содержатся %>
        <%# в поле errors модели (в нашем случае @users). %>
        <% if @user.errors.any? %>
            <div class="form-errors">
              <ul>
                <% for message in @user.errors.full_messages %>
                    <li class="form-error-message"><%= message %></li>
                <% end %>
              </ul>
            </div>
        <% end %>

        <div class="form-field">
          <%= f.label 'Цвет шапки', class: 'form-label' %>
          <%= f.color_field :head_color, class: 'form-color-field' %>
        </div>

        <%# С помощью методов label и text_field у объекта f мы создаем теги %>
        <%# <label ... > и <input type="text" ... > с нужными атрибуами %>
        <div class="form-field">
          <%= f.label :username, class: 'form-label' %>
          <%= f.text_field :username, class: 'form-text-field' %>
        </div>

        <%# Поступаем аналогично для других полей %>
        <div class="form-field">
          <%= f.label 'Ваше имя', class: 'form-label' %>
          <%= f.text_field :name, class: 'form-text-field' %>
        </div>

        <div class="form-field">
          <%= f.label 'URL вашей аватарки', class: 'form-label' %>
          <%= f.text_field :avatar_url, class: 'form-text-field' %>
        </div>

        <div class="buffer-top-large buffer-bottom">
          Если не хотите менять пароль — оставьте эти поля пустыми!
        </div>

        <div class="form-field">
          <%= f.label :password, class: 'form-label' %>
          <%= f.password_field :password, class: 'form-text-field' %>
        </div>

        <div class="form-field">
          <%= f.label :password_confirmation, class: 'form-label' %>
          <%= f.password_field :password_confirmation, class: 'form-text-field' %>
        </div>

        <div class="form-action buffer-top">
          <%= f.submit 'Сохранить', class: 'button button-dark button-small' %>
        </div>
    <% end %>
  </div>
</div>

app/views/users/index.html.erb
<%# Главная страница приложения %>

<div class="content-wrapper buffer-both text-center">
  <div class="buffer-both">
    <h1 class="title-medium">Наши пользователи</h1>
  </div>

  <%# Выводим ссылки-иконки всех пользователей и их имена %>
  <% @users.each do |user| %>
    <div class="users-list-item">
      <div class="user-title">
        <%= user.username %>
      </div>

      <div class="user-image-div user-image-div-small">
        <%= link_to image_tag(user_avatar(user), class: 'user-image'), user_path(user) %>
      </div>
    </div>
  <% end %>
</div>

<div class="content-wrapper buffer-both text-center">
  <h1 class="title-medium">Наши хэштеги</h1>
  <% all_hashtags = [] %>

  <%# Пробегаемся по всем вопросам и собираем в массив all_hashtags все хэштеги из вопросов %>
  <% @all_questions.each do |q| %>
    <% q.hashtags.each do |h| %>
      <% all_hashtags << h %>
      <% all_hashtags.uniq! %>
    <% end %>
  <% end %>

  <%# Выводим ссылки всех хэштегов %>
  <div class="text-hashtag">
    <% all_hashtags.each do |h| %>
      <%= link_to h.name, hashtag_path(h) %>
    <% end %>
  </div>
</div>

app/views/users/new.html.erb
<%# Страница для регистрации нового пользователя. %>

<div class="container content-wrapper buffer-both">
  <h1 class="title-medium">Присоединяйся к нам!</h1>

  <div class="column-1-2">
    <div class="form">
    <%# С помощью специального хелпера form_for мы делаем тег <form ...> %>
    <%# с нужными аттрибутами, после этого в переменной f будет специальный %>
    <%# объект (form builder object), вызывая методы которого мы можем %>
    <%# создавать теги для нужных нам полей формы. %>
    <%= form_for @user do |f| %>
      <%# Вывод ошибок валидации пользователя, если есть. Ошибки содержатся %>
      <%# в поле errors модели (в нашем случае @users). %>
      <% if @user.errors.any? %>
        <div class="form-errors">
          <ul>
            <% for message in @user.errors.full_messages %>
              <li class="form-error-message"><%= message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>

      <div class="form-field">
        <%= f.label 'Цвет шапки', class: 'form-label' %>
        <%= f.color_field :head_color, class: 'form-color-field' %>
      </div>
      <%# С помощью методов label и text_field у объекта f мы создаем теги %>
      <%# <label ... > и <input type="text" ... > с нужными атрибуами %>
      <div class="form-field">
        <%= f.label :email, 'Логин (email)', class: 'form-label' %>
        <%= f.text_field :email, class: 'form-text-field' %>
      </div>

      <%# Поступаем аналогично для других полей %>
      <div class="form-field">
        <%= f.label :username, 'Никнейм', class: 'form-label' %>
        <%= f.text_field :username, class: 'form-text-field' %>
      </div>

      <div class="form-field">
        <%= f.label :name, 'Имя', class: 'form-label' %>
        <%= f.text_field :name, class: 'form-text-field' %>
      </div>

      <div class="form-field">
        <%= f.label :password, 'Пароль', class: 'form-label' %>
        <%= f.password_field :password, class: 'form-text-field' %>
      </div>

      <div class="form-field">
        <%= f.label :password_confirmation, 'Пароль ещё раз', class: 'form-label' %>
        <%= f.password_field :password_confirmation, class: 'form-text-field' %>
      </div>

      <div class="form-action">
        <%= f.submit 'Зарегистрироваться', class: 'button button-small button-dark' %>
      </div>
    <% end %>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<%# Страница пользователя %>

<div class="user-header text-center" style="background: <%= @user.head_color %> ">

  <h1 class="title-medium">
    <%= @user.name %>
  </h1>

  <%# Ссылка на редактирование профиля %>
  <div class="buffer-both">
    <%= link_to 'Редактировать профиль', edit_user_path(@user) if current_user == @user %>
  </div>

  <%# Ссылка на удаление профиля %>
  <div class="buffer-both">
    <%= link_to 'Удалить профиль', user_path(@user), method: :delete, data: {confirm: 'Точно удалить профиль?'} if current_user == @user %>
  </div>

  <div class="user-image-div">
    <%= image_tag user_avatar(@user), class: 'user-image', alt: '[Фото]' %>
  </div>

  <h2 class="title-small buffer-both">
    @<%= @user.username %>
  </h2>
</div>

<div class="user-details">
  <div class="user-ask-button container text-center">
    <%= link_to "Спроси меня", '', class: 'button button-light', id: 'ask-button' %>
  </div>

  <%# Выводим счетчики вопросов в три колонки. Обратите внимание, что тут %>
  <%# в пору использовать наш любимый склонятор. На эту тему смотрите ДЗ. %>
  <div class="user-statistics container text-center">
    <div class="column-1-3">
      <h1 class="title-small"><%= @questions_count %></h1>
      <%= decline(@questions_count, "Вопрос", "Вопроса", "Вопросов") %>
    </div>
    <div class="column-1-3">
      <h1 class="title-small"><%= @answers_count %></h1>
      <%= decline(@answers_count, "Ответ", "Ответа", "Ответов") %>
    </div>
    <div class="column-1-3">
      <h1 class="title-small"><%= @unanswered_count %></h1>
      <%= decline(@unanswered_count, "Безответный", "Безответных", "Безответных") %>
    </div>
  </div>
</div>

<div class="user-question-form-div column-question-form" id='ask-form'>
  <div class="user-question-form buffer-both">
    <%= form_for @new_question do |f| %>
        <%= f.hidden_field :user_id %>

        <div class="form-field">
          <%= f.label "Ваш вопрос для @#{@user.username}", class: 'form-label' %>
          <%= f.text_area :text, class: 'form-textarea' %>
        </div>

        <%= recaptcha_tags %>

        <div class="form-action">
          <%= submit_tag 'Задать вопрос', class: 'button button-small button-dark' %>
        </div>
    <% end %>
  </div>
</div>

<div class="column-questions">
  <div class="user-questions buffer-both">
    <div class="questions-list">
      <% @questions.each do |question| %>
          <%= render partial: 'questions/question', object: question %>
      <% end %>
    </div>
  </div>
</div>